apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  ports:
  - port: 9000
  selector:
    app: php
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: php
spec:
  selector:
    matchLabels:
      app: php
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - image: mikiha/php7-fpm-alpine:1.4
        name: php
        env:
        ports:
        - containerPort: 9000
          name: php
